import type { Metadata } from "next";
import { connection } from "next/server";
// Self-hosted Geist (no build-time Google Fonts fetch).
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { AuthModalProvider } from "@/components/auth/AuthModalProvider";
import { RouteProgress } from "@/components/system/RouteProgress";
import { TermsGate } from "@/components/system/TermsGate";
import { Watermark } from "@/components/system/Watermark";
import { BugReporter } from "@/components/system/BugReporter";
import { CookieConsentBanner } from "@/components/cookies/CookieConsentBanner";
import { SiteFooter } from "@/components/layout/SiteFooter";
import { supabaseUrl } from "@/config/env";
import "./globals.css";

export const metadata: Metadata = {
  title: "Meino — Find your place near VSU",
  description:
    "Meino helps Visayas State University students find a boarding house that feels like home. Every option on one map, with real vacancies and honest walk times.",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // CSP nonces are generated by proxy for each request, so this layout cannot be
  // statically rendered at build time.
  await connection();

  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${GeistSans.variable} ${GeistMono.variable} h-full antialiased`}
    >
      <head>
        {/* Listing/ad photos load from Supabase Storage — warm the connection before
            the first <Image> request needs it. */}
        <link rel="preconnect" href={supabaseUrl} crossOrigin="anonymous" />
        <link rel="dns-prefetch" href={supabaseUrl} />
      </head>
      <body className="flex min-h-full flex-col">
        <RouteProgress />
        <TermsGate />
        <div className="flex-1">
          <AuthModalProvider>{children}</AuthModalProvider>
        </div>
        <SiteFooter />
        <Watermark />
        <BugReporter />
        <CookieConsentBanner />
      </body>
    </html>
  );
}
